# Builds (or serves) Tripper for the web with the Maps key from
# android/local.properties, so the key still lives in exactly one
# gitignored place. --dart-define feeds the Places HTTP calls; web/config.js
# feeds the Maps JavaScript API that index.html loads.
#
#   .\tool\build_web.ps1                 release build into build\web
#   .\tool\build_web.ps1 -Serve          run in Chrome against a dev server
#   .\tool\build_web.ps1 -BaseHref /app/ build for a hosted subpath
#
# Serving the result: build\web is a static site. It MUST be served over
# https (or http://localhost) — service workers, and therefore offline
# support and "Add to Home Screen" on iOS, are unavailable otherwise.

param(
    [switch]$Serve,
    [string]$BaseHref = '/'
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$propsPath = Join-Path $root 'android\local.properties'

$key = ''
if (Test-Path $propsPath) {
    $line = Get-Content $propsPath | Where-Object { $_ -match '^\s*MAPS_API_KEY\s*=' } | Select-Object -First 1
    if ($line) {
        $key = ($line -replace '^\s*MAPS_API_KEY\s*=\s*', '').Trim()
    }
}

if ([string]::IsNullOrWhiteSpace($key)) {
    Write-Warning 'MAPS_API_KEY not set in android/local.properties.'
    Write-Warning 'Maps will not load; the app falls back to its list views.'
}

# Every generated file here goes through WriteAllText with an explicit
# BOM-less encoder. Windows PowerShell's `Out-File -Encoding utf8` writes a
# UTF-8 BOM, and a BOM on sw.js makes Chrome refuse to register it ("an
# unknown error occurred when fetching the script") — i.e. it silently
# costs the app its entire offline story.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

# Regenerated every run so the built output never carries a stale key.
$configPath = Join-Path $root 'web\config.js'
$escaped = $key -replace "'", "\'"
$configBody = @"
// GENERATED by tool/build_web.ps1 - do not edit, do not commit.
window.tripperConfig = {
  mapsApiKey: '$escaped',
};
"@
[System.IO.File]::WriteAllText($configPath, $configBody, $utf8NoBom)

Push-Location $root
try {
    if ($Serve) {
        flutter run -d chrome "--dart-define=MAPS_API_KEY=$key"
    }
    else {
        # --no-web-resources-cdn is what makes this build work offline:
        # without it Flutter loads CanvasKit from gstatic.com at runtime,
        # so the very first flight-mode launch would render nothing.
        flutter build web --release --no-web-resources-cdn --base-href $BaseHref "--dart-define=MAPS_API_KEY=$key"

        # Name the service worker's cache after this build, so deploying
        # replaces every cached file instead of serving a mix of old and new.
        $swPath = Join-Path $root 'build\web\sw.js'
        $buildId = (Get-Date).ToUniversalTime().ToString('yyyyMMddHHmmss')
        $swBody = (Get-Content $swPath -Raw).Replace('__BUILD_ID__', $buildId)
        [System.IO.File]::WriteAllText($swPath, $swBody, $utf8NoBom)
        Write-Host "Service worker cache id: $buildId"

        Write-Host ''
        Write-Host 'Built build\web. Serve it over https (or http://localhost) —'
        Write-Host 'without a secure origin there is no service worker, so no'
        Write-Host 'offline support and no iOS "Add to Home Screen".'
    }
}
finally {
    Pop-Location
}
