# Downloads the web/sqlite3.wasm + web/drift_worker.js that match the drift
# and sqlite3 versions currently in pubspec.lock.
#
#   .\tool\update_web_db_assets.ps1
#
# Why this is a script and not a one-off download: those two files are
# compiled artifacts of the exact package versions we resolve against, and a
# mismatch does not fail the build — it fails at runtime, as an uncaught
# exception during database open, which on the web means a blank page. Run
# this after any `flutter pub upgrade` that moves drift or sqlite3.

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$lockPath = Join-Path $root 'pubspec.lock'

function Get-LockedVersion([string]$package) {
    $lines = Get-Content $lockPath
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match "^\s{2}$([regex]::Escape($package)):\s*$") {
            for ($j = $i + 1; $j -lt [Math]::Min($i + 10, $lines.Count); $j++) {
                if ($lines[$j] -match '^\s{4}version:\s*"([^"]+)"') { return $Matches[1] }
                # Next package entry: stop before reading someone else's version.
                if ($lines[$j] -match '^\s{2}\S') { break }
            }
        }
    }
    throw "Could not find a locked version for '$package' in pubspec.lock"
}

$driftVersion = Get-LockedVersion 'drift'
$sqliteVersion = Get-LockedVersion 'sqlite3'
Write-Host "drift $driftVersion / sqlite3 $sqliteVersion"

$targets = @(
    @{
        Url  = "https://github.com/simolus3/drift/releases/download/drift-$driftVersion/drift_worker.js"
        Path = Join-Path $root 'web\drift_worker.js'
    },
    @{
        Url  = "https://github.com/simolus3/sqlite3.dart/releases/download/sqlite3-$sqliteVersion/sqlite3.wasm"
        Path = Join-Path $root 'web\sqlite3.wasm'
    }
)

foreach ($target in $targets) {
    Write-Host "GET $($target.Url)"
    Invoke-WebRequest -Uri $target.Url -OutFile $target.Path -UseBasicParsing
    $size = (Get-Item $target.Path).Length
    Write-Host "  -> $($target.Path) ($size bytes)"
}

# Record what was fetched so a stale pair is visible in a diff.
$stampPath = Join-Path $root 'web\db-assets.txt'
@"
Generated by tool/update_web_db_assets.ps1 - do not edit by hand.
These two files must match the resolved package versions exactly; a
mismatch shows up only at runtime, as a failure to open the database.

drift_worker.js  drift $driftVersion
sqlite3.wasm     sqlite3 $sqliteVersion
"@ | Set-Content -Path $stampPath -Encoding ascii

Write-Host 'Done.'
